### ISSUE TITLE
Datepicker does not reset correctly / No distinction between today's date and selected date

### ISSUE THREAD

**Issue by Sigma-90** [chemerisuk/better-dateinput-polyfill#100]
I just ran into a problem that happens when the form that contains the date field gets cleared (something that happens very regularly in one-page web applications but sometimes even on regular forms - input[type="reset"] exists for a reason). Even forcing the change event after the date field was emptied with DOM.constructor(jQueryObject[0]).fire('change') had no result. I was able to at least remove the most obvious visual impact by executing a crude jQuery hack ( $('.btr-dateinput-value').removeAttr('datetime').html(''); ) to clear out the displayed date, but of course that doesn't reset the inner logic and so when I click into the date field once more, the previously selected date is highlighted instead of today's date.

Speaking of today's date: I noticed that the calendar changes which date gets the "today" class depending on the selection. That seems a bit odd. Shouldn't there be two distinct classes, one for "today" and one for "selected", so that today's date is always highlighted, but only in grey as long it is not currently selected as well? Almost all other calendars do that, and I'm sure a lot of people would appreciate it, if this one would as well.

**Comment by chemerisuk** [comment]
Version 3 uses ‘aria-*’ attributes instead of classes to highlight picker cells appropriately
