### ISSUE TITLE
Datepicker min and max values are not correctly updated. 

### ISSUE THREAD

**Issue by FeetInAncientTime** [chemerisuk/better-dateinput-polyfill#101]
Hello,
I've noticed a problem with the _min_ and _max_ values on the displayed date picker control.  From what I can see, if the attributes _max_ or _min_ are updated via javascript then these changes are not propagated to the date picker.  Please note, however that the initial values are correctly taken into account.

I've created a simple example to illustrate the problem : 

- https://jsfiddle.net/FeetInAncientTime/ww5p7tfL/4/

The basic idea of the pair of date inputs in the example is that it should not be possible to enter a start date that is later than the end date and vice versa.  The date picker should also be updated to reflect this.

After running the script, if you click on the start date input then you will see that the max limit is correctly set to the 30th June 2017.  Do not change the start date and click on the end date input.  You should see that the min limit is set to 1st June 2017.  The date picker correctly indicates that it is not possible to select the dates before or after the limits.

Re-run the script and click on the start date input.  Change the start date to 8th June 2017.  Click on the end date input and you will see that the min date has been set to the 8th June 2017.  However, if you click on the start date input you should see that the max date has not been altered.

I've deliberately tried to keep the code simple, but I apologise in advance if the problem is not related to the polyfill.  For information, I fire a change event in order to update the date picker (I noticed that this was necessary for a related problem that I had with the value attribute.)

Thanks for writing this polyfill !

**Comment by chemerisuk** [comment]
@FeetInAncientTime sorry for such a long reply. I believe the issue was fixed in the latest version, try updated demo https://jsfiddle.net/g6xL2pob/4/.
