### ISSUE TITLE
V3 doesn't work in IE 11

### ISSUE THREAD

**Issue by Teamop** [chemerisuk/better-dateinput-polyfill#106]
### Reproduce step:
Just open the demo in the repo in IE 11, the datepicker cannot be popped up and it's totally blank, even input something in the input, just blank and cannot see anything except the cursor moving.

**Comment by TylerRick** [comment]
Ouch. Just got bit by that too. Defeats the purpose of this polyfill if it doesn't work on IE11... :disappointed: 

Any ideas how to fix?

**Comment by TylerRick** [comment]
I also tried the latest v2 (https://github.com/chemerisuk/better-dateinput-polyfill/tree/v2.0.2) to see if it's just a problem with v3, but that had problems too: Although the picker appeared, the month and year were invisible (probably easy to fix with CSS) and worse, when you clicked on a date, it didn't seem to select it (no value appeared in the input).

So what is a person to use for a polyfill?

I also tried out https://github.com/brianblakely/nodep-date-input-polyfill but it doesn't seem to submit the value as yyyy-mm-dd.

In the past I would have turned to https://github.com/aFarkas/webshim but it looks like it is no longer maintained....

**Comment by Teamop** [comment]
@TylerRick I have used v2.0.2 for a long time without having problems.

**Comment by Lazza** [comment]
> month and year were invisible

@TylerRick did you import all the things correctly? Check out the archived demo, you need quite a few scripts but it works:

https://web.archive.org/web/20180402164909/http://chemerisuk.github.io/better-dateinput-polyfill/

**Comment by PadmapriyaVasudevan** [comment]
Hi,
I have added better-dateinput-polyfill in my project but it doesn't seem to work in IE 11.But in this link https://web.archive.org/web/20180402164909/http://chemerisuk.github.io/better-dateinput-polyfill/ its working in IE 11 works fine. To make it work anything needs to be modified or changed in the code.

**Comment by Teamop** [comment]
@PadmapriyaVasudevan use v2.0.2, not the latest v3

**Comment by PadmapriyaVasudevan** [comment]
@Teamop  Thanks much for your reply. Everything else is working as expected rather than data-format attribute. I am unable to modify the date format (mm/dd/yyyy)

**Comment by PadmapriyaVasudevan** [comment]
And also while submitting the value is not getting assigned to the formControlName.

**Comment by chemerisuk** [comment]
Fixed in v3.0.1. There some tweaks with the presented date presentation that have to be done, but it works at least on IE 10-11.

**Comment by PadmapriyaVasudevan** [comment]
@chemerisuk Thanks much for your reply.

**Comment by chemerisuk** [comment]
@PadmapriyaVasudevan I believe you have an error somewhere else. Everything is working on my side. In order to customize presented value try to add `data-format='{"month":"short","year":"numeric","day":"numeric"}'` on the element, for instance. Note: IE10 does not support Intl API, so the displayed value there is always the same, IE11 works well.

**Comment by rdm-dev09** [comment]
I tried pasting better-dom into the console in IE 11, and that worked fine. However, when I tried the same for the unminified better-dateinput-polyfill, I got the following error: 

SCRIPT5078: Cannot redefine non-configurable property 'value'
browsertools.console.js (141,7)

If we look at line 141 of the polyfill, we see this:

`Object.defineProperty(this[0], "value", {
        configurable: false,
        enumerable: true,
        get: valueDescriptor.get,
        set: this._setValue.bind(this, valueDescriptor.set, updateDisplayedText)
      });`

**Comment by chemerisuk** [comment]
Try to install files from npm as described in readme and check if there is a problem. I’ve never experienced such an issue.
