### ISSUE TITLE
valueAsDate is not setting value to date input and valueAsDate returns null instead of Date Object

### ISSUE THREAD

**Issue by parthivshah91** [chemerisuk/better-dateinput-polyfill#107]
I am not able to set date using valueAsDate property and valueAsDate does not return valid Date Object. 
I have attached demo file for the reference.
Duplicate of #95 
[index.zip](https://github.com/chemerisuk/better-dateinput-polyfill/files/2336074/index.zip)

**Comment by chemerisuk** [comment]
Fixed in v3.1.0
