### ISSUE TITLE
Calendar off by one

### ISSUE THREAD

**Issue by nickmelville** [chemerisuk/better-dateinput-polyfill#113]
Not the same issue as #79, as the selected date is entered into the input correctly, but the calendar itself is off by one day.

This is happening on my local dev site, but also on the github.io demo site for me. Chrome 72, Central Time (currently UTC -5), and it shows March 2019 starting on a Thursday when it actually started on a Friday:

![image](https://user-images.githubusercontent.com/869271/54770240-d3311200-4bd0-11e9-87fd-16e9539b1897.png)

Adding `"lang="en-US"` to the `html` element displays Saturday in the first column (which is opposite from what I would expect as Sunday is the first day of the week in the US), but the calendar dates are still off by one.

![image](https://user-images.githubusercontent.com/869271/54771055-7f272d00-4bd2-11e9-8fc0-716f10483a77.png)

Also, if you click on the month name, a couple odd things happen. First, the year is displayed as December - November, and second, selecting any month displays the calendar for the next month (e.g. selecting "March" displays the calendar for "April").

![image](https://user-images.githubusercontent.com/869271/54770828-032ce500-4bd2-11e9-9c2e-03d58f6973ea.png)

**Comment by chemerisuk** [comment]
@nickmelville thanks for details, I'll take a look.

**Comment by chemerisuk** [comment]
Try v3.2.4

**Comment by nickmelville** [comment]
Seems to have fixed the off by one issues, but now I see a couple others: 

1. The date format is "YYYY-MM-DD" regardless of what the `lang` attribute on `<HTML>` is set to. I also tried manually formatting the inputs with a `data-format` attribute per https://github.com/chemerisuk/better-dateinput-polyfill#change-default-date-presentation-format and that isn't working either.

Example: https://codepen.io/nickmelville/pen/YMwGOE

2. https://chemerisuk.github.io/better-dateinput-polyfill/build/better-dateinput-polyfill.js is returning 404, so your github.io demo page isn't working properly. :)

Thanks!

**Comment by chemerisuk** [comment]
Thanks, all should be fixed in v3.2.5

**Comment by nickmelville** [comment]
Looks great. Thanks!
