### ISSUE TITLE
Cannot read property 'getComputedStyle' of null

### ISSUE THREAD

**Issue by dertin** [chemerisuk/better-dateinput-polyfill#117]
I am using the input[type=date] in a popup that I show and hide, and this is causing the following problem:
https://github.com/chemerisuk/better-dom/issues/45

I'm not sure if the problem is from the library (better-dom) or the polyfill (better-dateinput-polyfill)

**Comment by MPriess** [comment]
@dertin Do you found a solution?

**Comment by MPriess** [comment]
I attached an example how to reproduce the problem.

[datepicker.zip](https://github.com/chemerisuk/better-dateinput-polyfill/files/3252799/datepicker.zip)

**Comment by chemerisuk** [comment]
Version 4 does not depend on `better-dom` so the issue should be fixed there.
