### ISSUE TITLE
Stuck on 1/1/1970 on Firefox 67 Windows

### ISSUE THREAD

**Issue by paulgreg** [chemerisuk/better-dateinput-polyfill#118]
Using Firefox 67.0 on Windows 7, the « start date » example is set on 1/1/1970 and can’t be changed.
Clicking on the field opens the calendar but no action (previous/next month, clicking on a date) is possible.

Firefox nightly 69 on linux don’t have the problem.

**Comment by jaweesner** [comment]
I looked into this a bit. It's due to firefox's flexible interpretation of the Date constructor. if the max/min attributes are not set, the Date constructor calls ```new Date("T00:00")``` which is interpreted as ```1970-01-01T08:00:00.000Z`` in firefox but ```Invalid Date``` in other broswers.  I'll open a PR.

**Comment by chemerisuk** [comment]
Fixed in v3.2.7

**Comment by paulgreg** [comment]
Thanks
