### ISSUE TITLE
Not working with bootstrap 3

### ISSUE THREAD

**Issue by garak** [chemerisuk/better-dateinput-polyfill#122]
Datepicker is not showing correctly when used in a bootstrap (version 3.4.1) form. The height is limited and only four weeks are visible

 If I remove bootstrap css, datepicker is working perfectly (e.g. like in provided demo).
Attached screenshot in Firefox 68 on Ubuntu (I also tried in Explorer 11 in Windows, it's even worse: I can see only three weeks)

![Senzanome](https://user-images.githubusercontent.com/179866/64121603-9c763f00-cd9f-11e9-8eea-a906ee5085b0.png)

I checked for old similar issues, none found

**Comment by devnix** [comment]
Believe it or not, I think it's the `font-size` attribute set by Bootstrap 3 on `html`.

It renders OK for me if I add this CSS because I'm setting my required font-size on `body`:
```css
html {
    font-size: initial;
}
```

**Comment by chemerisuk** [comment]
Fixed in v3.2.8
