### ISSUE TITLE
The calendar will not show it's full height

### ISSUE THREAD

**Issue by devnix** [chemerisuk/better-dateinput-polyfill#125]
Hi! I'm trying to implement your polyfill as this looks like the best solution I've found out there!

In our project, the <object> element seems like it's limiting the height of the calendar. I've tried to force the height. It works fine for lower values but once it reaches more than 210px, it will not increase anymore. May it be related to #122?

![image](https://user-images.githubusercontent.com/1777519/73440160-127fd180-4351-11ea-8465-d15c9f4f9156.png)

**Comment by devnix** [comment]
As I'm commenting on #122, it's solved by resetting the font on `html`:

```css
html {
    font-size: initial;
}
```

**Comment by chemerisuk** [comment]
@devnix thanks for the info. Do you mind to create a demo where the bug is reproduced? May be we can fix the issue in styles.

**Comment by devnix** [comment]
There you go! https://codepen.io/devnix/pen/bGNPVMz

**Comment by chemerisuk** [comment]
@devnix I've ended up using `px` units for `<dateinput-picker>`. It seems `rem` units changed when `font-size` modified on `<html>` element.

**Comment by devnix** [comment]
Nice, thank you so much!
