### ISSUE TITLE
BUG: Months displayed incorrectly: March showing twice

### ISSUE THREAD

**Issue by renedekat** [chemerisuk/better-dateinput-polyfill#126]
Steps to reproduce
1. Go to: http://chemerisuk.github.io/better-dateinput-polyfill/
2. Open calendar
3. Click on year

<img width="350" alt="Screenshot 2020-03-16 at 18 40 33" src="https://user-images.githubusercontent.com/8975204/76789924-c3cdb000-67b5-11ea-966b-211fb0f8ec53.png">

Browser: Safari Version 13.0.5 (15608.5.11)

**Comment by chemerisuk** [comment]
Hm, weird. 
<img width="760" alt="Screenshot 2020-03-17 10 18 04" src="https://user-images.githubusercontent.com/274044/76831686-d9d08480-6838-11ea-9513-8fd2e92b8deb.png">

What is your timezone?

**Comment by renedekat** [comment]
@chemerisuk My timezone is GMT (Ireland)

**Comment by chemerisuk** [comment]
@renedekat bugfix published in v3.2.9

**Comment by renedekat** [comment]
Thanks a million @chemerisuk
