### ISSUE TITLE
Use in the contect of webpack

### ISSUE THREAD

**Issue by thomasdarde** [chemerisuk/better-dateinput-polyfill#128]
Hello,

I was not able to use this polyfill with webpack, do you know if any resource exists showing how to do that ?

**Comment by chemerisuk** [comment]
@thomasdarde try to test v4 (demo at http://chemerisuk.github.io/better-dateinput-polyfill/). It has no dependencies so the setup should be easier - just include script file into your bundle.

**Comment by thomasdarde** [comment]
Thanks for the reply ! I did switch to https://www.npmjs.com/package/configurable-date-input-polyfill , but maybe it was only because I was not sufficiently familiar with webpack at the time
