### ISSUE TITLE
Tabbing into the date-field shows overlapping data in Firefox

### ISSUE THREAD

**Issue by Sebi2020** [chemerisuk/better-dateinput-polyfill#132]
Tested with version: 82.0.2 (64Bit - Version)

Maybe this bug is only present, if your browser is setup to use other   languages than English and therefore displaying dates with another format than YYYY-mm-dd.

The bug occurs only if you navigate to the date field with the <kbd>TAB</kbd> key.

**Comment by chemerisuk** [comment]
@Sebi2020 check v4 demo at http://chemerisuk.github.io/better-dateinput-polyfill/. I haven't seen such an issue in Firefox.

**Comment by Sebi2020** [comment]
Please re-read my issue description:
> this bug is only present, if your browser is setup to use other languages than English and therefore displaying dates with another format than YYYY-mm-dd.

Here you can see a screenshot showing the issue:
![error](https://user-images.githubusercontent.com/1862664/115159941-04bd8580-a096-11eb-99cb-fa6202cb0561.png)

**Comment by chemerisuk** [comment]
@Sebi2020 reopen the link to demo. Your screenshot is for old version 3, try to use version 4 instead.
