### ISSUE TITLE
Year selection would be better if it were by a dropdown, especially for entering dates of birth

### ISSUE THREAD

**Issue by kenguest** [chemerisuk/better-dateinput-polyfill#133]
For entering dates of birth, there could be a better ux than having to click on an arrow possibly up to 60 times or more.
It would be great if years could be selected from a drop-down selection.

**Comment by chemerisuk** [comment]
Year selection is improve in v4 that implements different UI. Check demo at http://chemerisuk.github.io/better-dateinput-polyfill/
