### ISSUE TITLE
Don't start on current Chrome

### ISSUE THREAD

**Issue by mikemaccana** [chemerisuk/better-dateinput-polyfill#23]
Current Chrome supports `input type=date` since Chrome 20, but better-dateinput-polyfill will still launch and override the default behavior on Chrome 39 and newer. 

http://caniuse.com/#feat=input-datetime

Maybe check 

    window.navigator.appVersion.match(/Chrome\/\d+/);

And avoid launching on Chrome versions past 20 (or whatever version we consider Chrome's date input to be good enough)

**Comment by chemerisuk** [comment]
The PR was merged
