### ISSUE TITLE
Is there a way to set the defaultValue?

### ISSUE THREAD

**Issue by mikemaccana** [chemerisuk/better-dateinput-polyfill#27]

**Comment by Orangetronic** [comment]
I find that if I either set a default value, or set the dateinput's value programmatically, it's not updating the display. The input's value does get set, it's just not updating the display. I'm not seeing any error messages, but it looks like onValueChanged isn't getting called when the value gets set by anything other than the calendar widget.

**Comment by chemerisuk** [comment]
@Orangetronic it won't work only if you use vanilla DOM APIs to update input value. In such case just trigger `change` event manually to notify about the change.

**Comment by Orangetronic** [comment]
What would that look like? If I call `element.dispatchEvent('change')` I get an "event provided is null" error…

**Comment by chemerisuk** [comment]
@Orangetronic yeah, vanilla DOM is not sexy. Alternatively you can use better-dom APIs:

```js
DOM.constructor(dateInputElement).fire("change");
```

**Comment by chemerisuk** [comment]
Should work properly I guess.

**Comment by mikemaccana** [comment]
Really sorry Maksim, at the time I was having the issue I was implementing
a last minute request from my manager just before Christmas and ended up
replacing the library rather than troubleshooting.

Again, sorry I reported this then didn't follow up with a good reproducible
test case. And thanks for a great library.

**Comment by chemerisuk** [comment]
@mikemaccana no problem. it's open source - nobody promises anything.

**Comment by mikemaccana** [comment]
It was still bad form. Thanks for understanding.
