### ISSUE TITLE
Support type=datetime and type=time, too

### ISSUE THREAD

**Issue by stefan-niedermann** [chemerisuk/better-dateinput-polyfill#30]
First let me say a greaaat thank you! You've done a fantastic job!
It's a shame, Firefox still does not support native date and time pickers on desktop yet.

It would be great, if you could support datetime and time as well, because the situation is not better there.

**Comment by chemerisuk** [comment]
@stefan-niedermann shame on IE too :)

For the time picker I have a separate [time picker polyfill](https://github.com/chemerisuk/better-timeinput-polyfill) which I haven't updated quite a long time... The main reason - I don't like current design solution, so I'm looking for a nice examples. Have you seen any good example for a time picker design?

Having date + time pickers both makes it trivial to enter a datetime value. So the priority of creating a separate polyfill for `[type=datetime]` is low in my list...

**Comment by stefan-niedermann** [comment]
> shame on IE too :)

thought we were talking about *browsers*? ;)

a nice design for a time picker would be this:

![2015-01-30_13h56_56](https://cloud.githubusercontent.com/assets/4741199/5975916/e2393eb2-a887-11e4-96d9-adfc91476d2f.png)

a click to an arrow jumps time 15 minutes.

of course it would be cool if the design would be similar to the date-picker - and a datetime-picker could display both "widgets" next to each other. Your opinion?

**Comment by chemerisuk** [comment]
let's move conversation to https://github.com/chemerisuk/better-timeinput-polyfill/issues/1
