### ISSUE TITLE
Data Format not applying in AngularJS

### ISSUE THREAD

**Issue by loganwedwards** [chemerisuk/better-dateinput-polyfill#34]
I have the following:
```html
<input id="dateStart" type="date" data-format="MM/dd/yyyy" value="2015-01-01" ng-model="..." />
```
I've also tried setting the `value` attribute in the JavaScript code using
```JavaScript
// $scope.dateQuery.startInput looks like YYYY-MM-dd format
document.getElementById('dateStart').setAttribute('value',$scope.dateQuery.startInput);
```

At any rate, the formatting is not being applied and was curious if this has been noticed. Anything specific that I can provide? I was thinking about wrapping this datepicker in an Angular directive, but wanted to hold off if I'm doing something obviously wrong.

Thanks!

**Comment by chemerisuk** [comment]
@loganwedwards hi. I believe you just need to trigger `change` event manually after any change you make. Angular has `$watch` method, that you can probably use to solve that problem.

**Comment by chemerisuk** [comment]
@loganwedwards also, if you prefer do it manually, do not update attribute `value` use __property__ instead:

```js
document.getElementById('dateStart').value = $scope.dateQuery.startInput;
```

**Comment by ysfjwd** [comment]
@loganwedwards any update on this?

**Comment by loganwedwards** [comment]
I apologize that this is way overdue, but after upgrading to 1.5.2, it seems the issue is resolved.

I don't need to trigger any special handlers, setup any watchers, etc... I may have had an old version of this library and or better-dom.

The syntax in the view is now simply:

```html
<input type="date" id="dateStart" name="dateStart" data-format="MM/dd/yyyy" ng-model="dateQuery.start"  />
```

Sorry for the trouble! Keep up the great work.

**Comment by chemerisuk** [comment]
@loganwedwards do you have any idea what has changed in Angular 1.5.2? Does it trigger `change` events by itself after value was updated?

**Comment by loganwedwards** [comment]
@chemerisuk Clarification, I upgrade better-dateinput-polyfill to 1.5.2.

**Comment by chemerisuk** [comment]
@loganwedwards ah, yes. alright, cool then
