### ISSUE TITLE
Minimiced version for bower install

### ISSUE THREAD

**Issue by BrodaNoel** [chemerisuk/better-dateinput-polyfill#35]
Hi!
Could you (I don't know how its work) add the minimiced version for bower installation?
I mean, when I install the plugin from bower, I should download the min-version.

See you!

**Comment by chemerisuk** [comment]
@BrodaNoel I agree, it will be nice to have. I'll include minified version into the next release.

**Comment by chemerisuk** [comment]
The changes have to be done in the separate repo https://github.com/chemerisuk/better-dom-boilerplate/issues/1
