### ISSUE TITLE
Placeholder doesn't work in Chrome

### ISSUE THREAD

**Issue by BrodaNoel** [chemerisuk/better-dateinput-polyfill#36]
Hi!
"placeholder attribute works as expected in browsers that support it".
Do Chrome support it? Because, check it:
http://www.catalogovaqueria.com/registro
Look the input left to the "Imagen de Perfil (Seleccionar)".
The placeholder is working well in Firefox, but the native support of Chrome is browking the placeholder.
Could you do something for that?

**Comment by chemerisuk** [comment]
@BrodaNoel correct, by default the polyfill uses native Chrome implementation, that doesn't support placeholders.

**Comment by BrodaNoel** [comment]
As I see, there is a attribute that you has added to the plugin to force the implementation of the polyfill instead of the native implementation.
Please, add the documentation about it.
