### ISSUE TITLE
Missing documentation to contrib

### ISSUE THREAD

**Issue by BrodaNoel** [chemerisuk/better-dateinput-polyfill#38]
Please, add documentation about how to contrib to the proyect.
I need to know what I need to run to build the code in the moment that I'm doing changes.
Are you using "grunt", "karma"? something?

My idea is run the command that I need to keep running (watching) and start edit files and that command should create the build after any change, so then I could refresh the index.html file and see the change.

Are you working on that way? Please, add documentation about it.

**Comment by chemerisuk** [comment]
@BrodaNoel I updated readme. Check it out and let me know if you have any question.
