### ISSUE TITLE
Error running contrin documentation

### ISSUE THREAD

**Issue by BrodaNoel** [chemerisuk/better-dateinput-polyfill#39]
Hi!
I run:
npm install -g gulp
and then
npm start

And I get:

0 info it worked if it ends with ok
1 verbose cli [ 'd:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'd:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart better-dateinput-polyfill@1.5.2
6 info start better-dateinput-polyfill@1.5.2
7 verbose unsafe-perm in lifecycle true
8 info better-dateinput-polyfill@1.5.2 Failed to exec start script
9 verbose stack Error: better-dateinput-polyfill@1.5.2 start: `gulp dev $npm_package_config_gulp`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (d:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (d:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1008:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
10 verbose pkgid better-dateinput-polyfill@1.5.2
11 verbose cwd D:\git\clients\better-dateinput-polyfill
12 error Windows_NT 6.1.7601
13 error argv "d:\\Program Files\\nodejs\\node.exe" "d:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v0.12.1
15 error npm  v2.5.1
16 error code ELIFECYCLE
17 error better-dateinput-polyfill@1.5.2 start: `gulp dev $npm_package_config_gulp`
17 error Exit status 1
18 error Failed at the better-dateinput-polyfill@1.5.2 start script 'gulp dev $npm_package_config_gulp'.
18 error This is most likely a problem with the better-dateinput-polyfill package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp dev $npm_package_config_gulp
18 error You can get their info via:
18 error     npm owner ls better-dateinput-polyfill
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by chemerisuk** [comment]
Did you run `npm install`?

**Comment by BrodaNoel** [comment]
No.
I didn't. The documentation doesn't said that hehe.
But, I just run it and I'm still having issues:

I'll paste here again the new log (I didn't check if is the same previous log)
0 info it worked if it ends with ok
1 verbose cli [ 'd:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'd:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart better-dateinput-polyfill@1.5.2
6 info start better-dateinput-polyfill@1.5.2
7 verbose unsafe-perm in lifecycle true
8 info better-dateinput-polyfill@1.5.2 Failed to exec start script
9 verbose stack Error: better-dateinput-polyfill@1.5.2 start: `gulp dev $npm_package_config_gulp`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (d:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (d:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1008:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
10 verbose pkgid better-dateinput-polyfill@1.5.2
11 verbose cwd D:\git\clients\better-dateinput-polyfill
12 error Windows_NT 6.1.7601
13 error argv "d:\\Program Files\\nodejs\\node.exe" "d:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v0.12.1
15 error npm  v2.5.1
16 error code ELIFECYCLE
17 error better-dateinput-polyfill@1.5.2 start: `gulp dev $npm_package_config_gulp`
17 error Exit status 1
18 error Failed at the better-dateinput-polyfill@1.5.2 start script 'gulp dev $npm_package_config_gulp'.
18 error This is most likely a problem with the better-dateinput-polyfill package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp dev $npm_package_config_gulp
18 error You can get their info via:
18 error     npm owner ls better-dateinput-polyfill
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by BrodaNoel** [comment]
So, sumarizing.
I run:
npm install -g gulp
npm install
(here, without errors)
npm start
And here I get the prev log.

**Comment by chemerisuk** [comment]
Locally I use node 0.11, you can try it instead of 0.12

**Comment by BrodaNoel** [comment]
I'm using node 0.12.1
And I'm using Windows 7.
If I run "gulp dev", should I see something? I'm getting a "No gulpfile found".

**Comment by BrodaNoel** [comment]
I run:
gulp --gulpfile node_modules/better-dom-boilerplate/gulpfile.js --cwd .
And as I see, it's running properly, but, npm start should do it automatically. Right?

**Comment by chemerisuk** [comment]
@BrodaNoel correct, `npm start` is an alias for that command. Not sure why it doesn't work on your side.

**Comment by BrodaNoel** [comment]
WE should try a new isolated environment

Firma Automática:
Mail enviado desde mi teléfono móvil. Disculpe los errores y el formato.

**Comment by chemerisuk** [comment]
@BrodaNoel nevermind. just run `gulp --gulpfile node_modules/better-dom-boilerplate/gulpfile.js --cwd .` instead if it works on your side.

**Comment by chemerisuk** [comment]
@BrodaNoel I had to reinstall `gulp`, but it works for me on node 0.12.2

**Comment by chemerisuk** [comment]
@BrodaNoel does the problem still exist on your side?

**Comment by BrodaNoel** [comment]
@chemerisuk .
I just updated `node` and `npm`.
I run:
`npm update -g`
`npm cache clear`
`npm install`
`npm install gulp`
`npm start`

And I get what you see in this file:
![untitled](https://cloud.githubusercontent.com/assets/1837969/7421939/292d8ab2-ef5f-11e4-9da5-66ee37de12fd.png)

I reeeeeally want to help with that new feature: https://github.com/chemerisuk/better-dateinput-polyfill/issues/8 but I can't start develop :-1:

**Comment by BrodaNoel** [comment]
You should show me which versions are you using in your local and global packages. That could be the issue. I'll try to install the same versions as you and check what's happend.

**Comment by BrodaNoel** [comment]
Note: Working properly in Windows 7. Issues in Windows 8.

**Comment by chemerisuk** [comment]
@BrodaNoel I have no idea why you have been experiencing this problem. May be it's a NPM bug.
