### ISSUE TITLE
Doesn't help in JavaFX WebView

### ISSUE THREAD

**Issue by arapoport** [chemerisuk/better-dateinput-polyfill#40]
Hi!

Thanks for a nice library!

I found a minor problem. It seems to be that it does not work for JavaFX's WebView. JavaFX lacks native date-picker, but better-dateinput-polyfill does nothing about it.

Under Java 8 the date input field cannot be edited at all (JavaFX's bug, the dropdown box doesn't open) and under Java 7 a simple text field is displayed. (JavaFX has own versioning, it can that it does not depend directly on the Java version).

Maybe you can do something about it.

![javafx-java7](https://cloud.githubusercontent.com/assets/3393725/6941564/410c7296-d881-11e4-80a1-e76deb5a2eb1.PNG)

![javafx-java8](https://cloud.githubusercontent.com/assets/3393725/6941527/fe971f7e-d880-11e4-9658-db422f753834.PNG)

**Comment by chemerisuk** [comment]
@arapoport Have you tried to use `data-native="desktop"` on input to [suppress feature detection](https://github.com/chemerisuk/better-dateinput-polyfill#forcing-the-polyfill)?

**Comment by arapoport** [comment]
@chemerisuk Thanks for the tip! JavaFX runs on desktops so I tried `data-native="mobile"` and it worked. It sill forces the widget for all desktop browsers, but for my case it is not a problem.

JavaFX uses Webkit for the WebView, but one of the older versions and does not support many HTML5-features. I assume, that better-dateinput-polyfill thinks it is a Chrome with an own native control and does not interfere until forced.

**Comment by chemerisuk** [comment]
@arapoport old WebKit has a bug with returning value of `type` field that I use to perform the feature detection (more info here http://www.quirksmode.org/blog/archives/2015/03/better_modern_i.html). In the next release I'll try to handle it properly.
