### ISSUE TITLE
Input field stripped of ::after pseudo-element

### ISSUE THREAD

**Issue by sniggitysnax** [chemerisuk/better-dateinput-polyfill#42]
I am using the data-native="mobile" attribute to force desktop to use the polyfill calendar. I have style that places an icon on the ::after psuedo-element of my input field. Upon page load, the ::after pseudo-element and it's relating styles are absent.

**Comment by chemerisuk** [comment]
@sniggitysnax need a screenshot

**Comment by sniggitysnax** [comment]
Before: 
![screen shot 2015-04-09 at 2 33 02 pm](https://cloud.githubusercontent.com/assets/1430042/7075187/9218857c-dec5-11e4-8a40-228e1d45aa3d.png)

After:
![screen shot 2015-04-09 at 2 33 33 pm](https://cloud.githubusercontent.com/assets/1430042/7075196/9c80e34c-dec5-11e4-878a-be0ca2ce6c8a.png)

**Comment by chemerisuk** [comment]
@sniggitysnax try to set `position:relative` and appropriate `z-index` value on the pseudo-element.

**Comment by sniggitysnax** [comment]
I tried that to no avail. Upon page load, it flashes the desired icon and then disappears. 
Also, here is the input field without forcing the polyfill:
```html
<input id="datePicker" class="form--control" type="date" value="2015-04-08" min="2015-04-08" data-format="MM/dd/yyyy">
  ::after
</input>
```
and after (with the polyfill):
```html
<input id="datePicker" class="form--control" type="text" value="2015-04-08" min="2015-04-08" data-native="mobile" data-format="MM/dd/yyyy" style="color: transparent;">
```

**Comment by chemerisuk** [comment]
Ah, you are styling input's ::after? Bad idea, it doesn't work is all browsers. Use  `background-image` instead with an appropriate svg.

**Comment by sniggitysnax** [comment]
We are using this on a mvp project and styling ::after is working fine in other instances as well as this instance prior to forcing the polyfill.

**Comment by sniggitysnax** [comment]
Thank you for your prompt replies thus far!

**Comment by chemerisuk** [comment]
@sniggitysnax anyway I'd suggest to use `background-image` instead. Styling `::after` is hacky for this use-case (and quirky). Not sure if I can help.

**Comment by sniggitysnax** [comment]
Okay. Thank you for your feedback. I will see what I can come up with.

**Comment by sniggitysnax** [comment]
I do see in many references that input type="text" has quirkiness with the ::after pseudo-element in particular.
