### ISSUE TITLE
bug on "line-height" calculation

### ISSUE THREAD

**Issue by DaBourz** [chemerisuk/better-dateinput-polyfill#46]
I found a bug on line-height calculation on line 62 :

https://github.com/chemerisuk/better-dateinput-polyfill/blob/master/dist/better-dateinput-polyfill.js#L62

Using some collapsable or hidden elements at start with Bootstrap (like basic collapsed panels or modal) it seems that the line-height calculation is returning a wrong 0 rather than the default Bootstrap value (aka34px).

Commenting line 62 did the trick for me :

//"line-height": offset.height + "px",

but I don't know why / if it has any side effects.

Stéphane

**Comment by chemerisuk** [comment]
@DaBourz thanks for reporting Stéphane. You could also override inline styles via `!important` without modification of the source. But I agree - this is a edge case that should be handled properly.
