### ISSUE TITLE
Example isn't working at all

### ISSUE THREAD

**Issue by LC43** [chemerisuk/better-dateinput-polyfill#49]
Tried to update to the new version, but it doesn't trigger at all, just like the demo.

**Comment by fagnercarvalho** [comment]
What browser you are using?
It seems to be working in both last version of Chrome and Firefox.

**Comment by LC43** [comment]
Hi and thanks for your help.

i'm using chrome Version 45.0.2438.3 dev (64-bit), on linux. it doesn't have any weird flag because i use it to test our websites.

**Comment by fagnercarvalho** [comment]
I don't know for sure but I think it's suppose to be like this because the demo isn't forcing the polyfill from the plugin. 
If you go [here](https://github.com/chemerisuk/better-dateinput-polyfill#custom-formats) and [here](https://github.com/chemerisuk/better-dateinput-polyfill#forcing-the-polyfill) you are going to see more about how to format the date and force the polyfill, respectively.
Oh, and FYI I got the exact same behavior in my version of Chrome.

**Comment by LC43** [comment]
i though it was the other way around, that you can force having a *native* support:

_For example, the code below defines a dateinput that uses a native implementation on mobile phones, but ALL desktop browsers (even Chrome desktop) will have a consistent widget created by the polyfill._

`<input type="date" data-native="mobile" name="foo" value="bar">`

if you click onit, does it open the plugin's calendar?

**Comment by fagnercarvalho** [comment]
Yes, it does. Using this code snippet I can see the plugin's calendar even in Chrome as was stated in the text above.

**Comment by LC43** [comment]
![screenshot-chemerisuk github io 2015-07-08 05-49-37](https://cloud.githubusercontent.com/assets/48201/8563301/2887684c-2535-11e5-841a-8aae94f1f8ae.png)


on firefox i get the plugin calendar and the placeholder is showing too.

**Comment by fagnercarvalho** [comment]
Yep, same as me.
I think Firefox don't have full support for date input yet so that's why the plugin's polyfill is being used by default.

**Comment by LC43** [comment]
that makes sense!

so, how did you force it to show on chrome?

**Comment by fagnercarvalho** [comment]
I use the ```data-native="mobile"``` property as I said before.

**Comment by chemerisuk** [comment]
Read docs guys ;)
