### ISSUE TITLE
IE9 & lower not working

### ISSUE THREAD

**Issue by chrislachance** [chemerisuk/better-dateinput-polyfill#53]
Just an FYI on the demo provided, IE9 is throwing a "Unable to get property 'split' of undefined or null reference" on File: better-dom.js, Line: 84, Column: 45. Nothing appears in the input field because of that.

IE8 is throwing a "Object doesn't support property or method 'addEventListener'" on File: better-dom.js, Line: 512, Column: 21, but does display the default date.

**Comment by chemerisuk** [comment]
@chrislachance True, online demo does not work in IE<10 because of CORS, but the polyfill does work in that browsers locally, if you add extra files (https://github.com/chemerisuk/better-dom#notes-about-old-ies).
