### ISSUE TITLE
Timezone confusion

### ISSUE THREAD

**Issue by cstorey** [chemerisuk/better-dateinput-polyfill#55]
Issue #9 implies that there has been some confusion over time-zones. We're seeing the exact same issue, but because we're on BST (+01:00), we're not seeing great results.

Helpfully, we're only seeing this on Chromium versions between `v46.0.2454.13` and `48.0.2536.0`, wheras `48.0.2537.0` and `v46.0.2454.13` fail.

For example, if we instantiate a element with `max=2015-10-16`; then when it comes to run #_changeValue, we call readDateRange. This returns an array with an end point of `new Date('2015-10-16')` -> `Fri Oct 16 2015 00:00:00 GMT+0100 (BST)`, or 2015-10-15T23:00+00:00.

I've found that if I replace the calls to `getUTCMonth/getUTCDate/getUTCFullYear` in `_formatValue` to the non-utc equivalents, then that does mean that the widget does at least then render the correct date. However, I've not invested far enough to tell what other implications this would have.

**Comment by gergderkson** [comment]
+1 also being affected by this. Any updates on it?

**Comment by chemerisuk** [comment]
@cstorey when `Date` constructor argument is an ISO string, then UTC timezone is used (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse). Therefore I didn't fully understand your use case. Could you describe it in more details?

**Comment by chemerisuk** [comment]
@cstorey true, faced that bug as well. Fixed in https://github.com/chemerisuk/better-time-element which the next version will depend on.

**Comment by chemerisuk** [comment]
Fixed in ecf60ef0f8e7a36111140fcae5ad110077503029
