### ISSUE TITLE
Support for input[type=month]

### ISSUE THREAD

**Issue by md5** [chemerisuk/better-dateinput-polyfill#59]
Do you have any plans to support `<input type="month">`? I naively used this polyfill thinking it would support `month` fields, but it looks like it doesn't. I think you've done a great job otherwise, but I need to figure out whether we need to switch to a different polyfill with `month` support.

**Comment by chemerisuk** [comment]
Hi @md5 . I think it can be done in scope of https://github.com/chemerisuk/better-dateinput-polyfill/issues/8 thought not sure when I'll back to Open Source... May be next year :)

**Comment by md5** [comment]
Thanks. I appreciate your response nonetheless.

**Comment by chemerisuk** [comment]
@md5 we could add support for `[type=month]` in version 2... Do you need in your case the ability to limit input to months only?

**Comment by md5** [comment]
No, we were looking for Month+Year

**Comment by chemerisuk** [comment]
Alright, then I believe the feature https://github.com/chemerisuk/better-dateinput-polyfill/issues/8 should solve your problem too.
