### ISSUE TITLE
Trailing period on "MMM" months

### ISSUE THREAD

**Issue by md5** [chemerisuk/better-dateinput-polyfill#60]
The docs don't mention that there is a trailing "." on `MMM` values, but it's hard coded in `main.js`. It would be great if there were a way to omit this period.

**Comment by chemerisuk** [comment]
@md5 hm, for displayed values months do not have the dot suffix (https://github.com/chemerisuk/better-time-element/blob/master/dist/better-time-element.js#L133). On the other case I'm not sure if understood your issues correctly...

**Comment by md5** [comment]
Does that rely on calling `DOM.set("lang", "en")` somewhere? It's been a while since I encountered this issue, but I believe we were seeing a trailing period on the short month names.

**Comment by chemerisuk** [comment]
If you have `<html lang="en">` you don't need to call `DOM.set("lang", "en")`. Languages like `en_US` should work properly as well.

**Comment by md5** [comment]
Thanks @chemerisuk
