### ISSUE TITLE
NPM version?

### ISSUE THREAD

**Issue by mheiber** [chemerisuk/better-dateinput-polyfill#62]
Could you make a version for NPM for use with Webpack and Browserify?

**Comment by chemerisuk** [comment]
@mheiber Planned in version 2

**Comment by TheLarkInn** [comment]
+1 Would be nice to have this as an NPM module. :-D

**Comment by chemerisuk** [comment]
v2.0.0-rc.2 was published to NPM https://www.npmjs.com/package/better-dateinput-polyfill
