### ISSUE TITLE
Bower Install Failing from github ref

### ISSUE THREAD

**Issue by TheLarkInn** [chemerisuk/better-dateinput-polyfill#65]
When I attempted to install using: 

`bower install better-dateinput-polyfill` 

I got the following error: 

```
bower better-dateinput-polyfill#*          ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/chemerisuk/better-dateinput-polyfill.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.130]: errno=Connection refused
```

Attached below is a copy of the console error. 

![screen shot 2016-03-04 at 10 31 28 am](https://cloud.githubusercontent.com/assets/3408176/13533035/32b98436-e1f4-11e5-8bbc-eb5be0d22e64.png)

**Comment by TheLarkInn** [comment]
Does this maybe need to use the `https:` git url.

**Comment by chemerisuk** [comment]
@TheLarkInn I believe you had an issue with internet connection.
