### ISSUE TITLE
Picker not showing on dynamically created input

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [chemerisuk/better-dateinput-polyfill#67]
I create a form dynamically using javascript and I use bootstrap.

input[type=date] is not showing a picker (tested in Firefox and Internet Explorer 11).

![issue_1](https://cloud.githubusercontent.com/assets/10342708/14345823/72c24c36-fcaf-11e5-93ca-71d22ce9d03e.PNG)
![issue_2](https://cloud.githubusercontent.com/assets/10342708/14345824/7506924a-fcaf-11e5-8189-ebaa2c0bf131.PNG)

**Comment by chemerisuk** [comment]
@0xFEEDC0DE64 would you mind to setup a demo page on jsbin/fiddle etc. to investigate the issue? Thanks

**Comment by chemerisuk** [comment]
@0xFEEDC0DE64 could you check if version 2 works on your side?
