### ISSUE TITLE
Update docs for version 2

### ISSUE THREAD

**Issue by chemerisuk** [chemerisuk/better-dateinput-polyfill#68]
- [x] document `data-polyfill` attribute
- [ ] document relation to the `better-time-element`

**Comment by tomhicz** [comment]
Are better-time-element and better-emmet-plugin needed? If so, which versions? 

They are mentioned in the docs, but weren't downloaded by "bower install better-dateinput-polyfill". 

Installing them standalone through bower leads to a bunch of version conflict choices as different versions are required by different modules, so right now I'm getting javascript errors and obviously made bad choices. 

PS/ On the docs:  "For example, the code below defines a dateinput that uses a native implementation on mobile phones, but ALL desktop browsers (even Chrome desktop) will have a consistent widget created by the polyfill." is <input type="date" data-polyfill="mobile">? or should it be <input type="date" data-polyfill="desktop">?

**Comment by tomhicz** [comment]
Ah, ok, I've worked it out. bower is installing an older version that doesn't match the one in the docs. Hence only 
<script src="bower_components/better-dom/dist/better-dom.js"></script>
<script src="bower_components/better-i18n-plugin/dist/better-i18n-plugin.js"></script>
<script src="bower_components/better-dateinput-polyfill/dist/better-dateinput-polyfill.js"></script>
is needed, but the data-polyfill mobile/desktop options don't appear to work on that version. 

To install the latest version, mentioned in the docs needs
`bower install better-dateinput-polyfill#2.0.0-rc.4`
which seems to work with the data-polyfill mobile/desktop options but has weird positioning issues that I'll have to investigate. 

Anyway, for those of us who aren't fully up to date with bower, it might be worth updating the docs to explain that they refer to the latest dev version, but bower will install an older version.

**Comment by chemerisuk** [comment]
@tomhicz thank for the notice. The version 2 will be released soon, and it should solve confusion in the docs.

**Comment by erfanimani** [comment]
Thanks for that @tomhicz

**Comment by chemerisuk** [comment]
Version 2.0.0 should be available at bower now.
