### ISSUE TITLE
Incompatibility with jQuery show/hide

### ISSUE THREAD

**Issue by LBreda** [chemerisuk/better-dateinput-polyfill#69]
Hi,

This is probably not a bug, but maybe someone can help me about it.

I'm using better-dateinput-polyfill in a complex form. Some of the date fields are conditiolally shown/hidden with the jQuery .show() and .hide() methods.

better-dateinput-polyfill seems to be incompatible with these methods: after I .show() a date input, it does not show the date. Is there a workaround?

**Comment by chemerisuk** [comment]
@LBreda could you try to upgrade the polyfill to version 2 and check if it helps to solve the problem. There were some enhancements made related to hidden dateinput fields.

**Comment by LBreda** [comment]
I tried the last RC just before my message. It does not show the month, and
it doesn't show the date. O__o

>

**Comment by chemerisuk** [comment]
@LBreda have you included all required script files? There is one more dependency in version 2 on better-time-element

**Comment by LBreda** [comment]
@chemerisuk I included better-emmet-plugin and all of the required files for the stable version. I now solved the issues moving the fields on a negative absolute position instead of hiding them. It's a ugly workaround, but it is working.

**Comment by chemerisuk** [comment]
@LBreda would you mind to setup a demo with your use case on jsbin/fiddle? I could look at the problem then.

**Comment by LBreda** [comment]
Uhm, I could not reproduce the exact behavior on jsfiddle (it requires a lot of garbage). This fiddle has a related behavior, thoug: https://jsfiddle.net/lbreda/vtpptvme/4/

If I populate one of the two fields, and I change the field I show, the other field seem populated too. It seems that it still show the "polyfill part" of the field, while changing the fake input on the background.

**Comment by chemerisuk** [comment]
@LBreda okay, I think the issue is clear for me. The polyfill adds extra HTML into markup, so if you call `$("[type='date']").hide();` then you only hide the actual input without those extra HTML elements added by polyfill. That why you might have the confusion.

**Comment by LBreda** [comment]
OK. What is the actual element to .hide()?

Il giorno mer 13 apr 2016 alle ore 12:27 Maksim Chemerisuk <
notifications@github.com> ha scritto:

**Comment by chemerisuk** [comment]
Something like below should work:
```js
$("#a").show().prev(".btr-dateinput-value").show().prev(".btr-dateinput-calendar").show();
```
Check out the demo: https://jsfiddle.net/vtpptvme/7/

**Comment by LBreda** [comment]
It works.

The real thing was a little more complicated, tough, as I was using
bootstrap and its row/col system. If I use show/hide on a row containing
the date input, it does not work.
