### ISSUE TITLE
Ability to clear the field

### ISSUE THREAD

**Issue by LBreda** [chemerisuk/better-dateinput-polyfill#70]
Is there a way to clear the field after selecting a date? Something like the small "x" you can find in the Chrome datepicker.

**Comment by chemerisuk** [comment]
You can use BACKSPACE/DELETE key to clear current value. Though I've noticed at present it only clears current selection in calendar but not the input value, will be fixed in the next version. Adding a separate clear button is a nice to have feature, not for release 2 I think.

**Comment by chemerisuk** [comment]
Published fix in better-time-element, so BACKSPACE/DELETE keys work properly now. Check demo at http://chemerisuk.github.io/better-dateinput-polyfill/

**Comment by LBreda** [comment]
It works pretty good, thank you very much. It introduced a new error, tough. If I click on the current month to change it, I get this: http://imgur.com/ZoSDDax

**Comment by chemerisuk** [comment]
@LBreda hm, I can't figure out steps to reproduce the issue. Have you updated all related plugins? Does the bug exist on the online demo as well?

**Comment by LBreda** [comment]
Yes, the bug exists on the online demo as well. I get it on Firefox, both on the Debian and Windows versions. 

Screenshot: http://imgur.com/dpquijp

**Comment by chemerisuk** [comment]
Alright, I think I got it. Should be fixed in v2.0.0-rc.4 :)

**Comment by LBreda** [comment]
Thank you!

Il giorno mar 19 apr 2016 alle ore 13:30 Maksim Chemerisuk <
notifications@github.com> ha scritto:
