### ISSUE TITLE
Input picker offsets day picked by -1 

### ISSUE THREAD

**Issue by cbillen** [chemerisuk/better-dateinput-polyfill#72]
On your demo page
http://chemerisuk.github.io/better-dateinput-polyfill/

Using Safari 9.1 or Chrome 49 on Mac OS X 10.11

If I pick any date, say September 1st 2000, then the date rendered in the picker is August 31, 1999

What could be causing this?

**Comment by chemerisuk** [comment]
@cbillen Hi. What is your time zone?

**Comment by cbillen** [comment]
GMT-6 Chicago CST

[image: WarmlyYours] <http://www.warmlyyours.com>
[image: Facebook] <http://www.facebook.com/warmlyyours> [image: Twitter]
<http://www.twitter.com/warmlyyours> [image: LinkedIn]
<http://www.linkedin.com/company/warmlyyours>
Christian Billen
Director of IT
*P:* (800) 875-5285 x 800 *F:* (800) 408-1100
Tell us how we're doing
<https://www.warmlyyours.com/survey/customer-satisfaction/quick-survey-25>
and receive $25 off your next order!
<http://www.houzz.com/pro/warmlyyours1>
<http://www.houzz.com/pro/warmlyyours1> [image: SEN 2015 Vendor of the Year]

On Sat, Apr 23, 2016 at 7:39 AM, Maksim Chemerisuk <notifications@github.com

**Comment by chemerisuk** [comment]
The bug was fixes in version 2
