### ISSUE TITLE
Calendar positioned OVER input on firefox, but under on chrome?

### ISSUE THREAD

**Issue by tomhicz** [chemerisuk/better-dateinput-polyfill#73]
I've added the 2.0.0-rc.4 to my form, and it seems to work in both firefox and chrome on desktop. 

In chrome the calendar box is usually positioned under the input, but moves above when there is no space. However in firefox the caledar box seems to be always positioned above the input, even when there is no reason or no space. 

The demo page works correctly in both browsers, so I'm not sure what the issue is. 
I'll try to eliminate things.

**Comment by chemerisuk** [comment]
@tomhicz could you paste your HTML?

**Comment by tomhicz** [comment]
The following (inside a form) makes the popup always appear above the box in firefox:

`                    <label>Departure time: 
                    <select name="Departure time" size="1">
                        <option value="" selected>(Select departure time)</option>
                    </select></label>

                    <label for="departuredate">Departure date:</label>
                     <input name="departure date" id="departuredate" type="date" size="22" data-polyfill="desktop">`

but the following makes it appear below the box:
`                    <label>Departure time: 
</label>

                    <label for="departuredate">Departure date:</label>
                     <input name="departure date" id="departuredate" type="date" size="22" data-polyfill="desktop">`

I've tried disabling styles in-browser to see what works, but it's hard to get consistent results... it seems like the position is stored somewhere, so even if I change things on-page, the location doesn't move.

**Comment by renegeuze** [comment]
In ` if (HTML.clientHeight < offset.bottom + pickerOffset.height) {` offset.bottom includes the scroll position(see better-dom.js)
If it would just use `getBoundingClientRect().bottom` it would actually work.

The reason it works in the demo - it's not a high enough page to scroll.
