### ISSUE TITLE
UNIX epoch is invalid

### ISSUE THREAD

**Issue by greenyouse** [chemerisuk/better-dateinput-polyfill#75]
Hi, I noticed that entering 1970-01-01 made the input use the current date. There were a few checks that used `.getTime()` which would fail if the UNIX epoch was used since the result would be 0, which is false.

https://github.com/chemerisuk/better-dateinput-polyfill/blob/master/src/main.js#L87

I can send over a pull request if this looks OK to change.

**Comment by chemerisuk** [comment]
Please do. It seems like you just need to use 'isNaN' instead of that falsy check: http://stackoverflow.com/questions/1353684/detecting-an-invalid-date-date-instance-in-javascript

**Comment by chemerisuk** [comment]
Fixed in https://github.com/chemerisuk/better-dateinput-polyfill/pull/77
