### ISSUE TITLE
How to click to change year & month

### ISSUE THREAD

**Issue by nvcken** [chemerisuk/better-dateinput-polyfill#8]
Could not click on month or year to change on the calendar popup ?

**Comment by rjanot** [comment]
Hi,

+1, this would be a really great feature

Will check If I can help and do a PR soon

**Comment by chemerisuk** [comment]
@rjanot I do appreciate your help. Let me know if you have any question.

Currently I stuck with IE8 that has some problems with code in the master branch. As soon as those problems are resolved I'll publish a new version.

**Comment by darren131** [comment]
Hi,

Just wondering if you've managed to get onto this?

Thanks
Darren

**Comment by chemerisuk** [comment]
@darren131 sorry, I don't have free time on this feature for now.

**Comment by darren131** [comment]
Understand :) Thanks anyway – it's a great product! :)

On 18 March 2015 at 21:51, Maksim Chemerisuk <notifications@github.com>
wrote:

> @darren131 <https://github.com/darren131> sorry, I don't have free time
> on this feature for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chemerisuk/better-dateinput-polyfill/issues/8#issuecomment-82825080>
> .
>



-- 
Darren Wood • The Fold
+64 21 78 45 78

**Comment by BrodaNoel** [comment]
@chemerisuk, Could you do a quicky sumarize here about: "What I should do to add this behavior?", so, I could work on it and send a pull request.

**Comment by chemerisuk** [comment]
@BrodaNoel Well, you have to look at the existing source code... And implement this enhancement :) Not sure what details I can provide.

**Comment by BrodaNoel** [comment]
I'm working on it right now.
I hope send a PR in a few days for "month displayer" at last... And then I'll continue working with the "year displayer"

![sin titulo](https://cloud.githubusercontent.com/assets/1837969/7428712/9dee267e-efcb-11e4-9eb0-101efbf8ef89.png)

**Comment by chemerisuk** [comment]
@BrodaNoel :+1:

**Comment by fagnercarvalho** [comment]
I was really needing this one :(

**Comment by sgentile** [comment]
This would really solidify the polyfill   +1 !

**Comment by md5** [comment]
@BrodaNoel I see you have a branch or two where you started working on these changes (e.g. https://github.com/chemerisuk/better-dateinput-polyfill/compare/master...BrodaNoel:new-feature-change-month-and-year). It looks like you haven't worked on it for a few months, but I wanted to check whether you think this is something you might work on again in the near future.

**Comment by mnebuerquo** [comment]
I want to use this for users to enter their birthdate when creating an account. This is so I can prevent children under age 13 from joining the site because of [COPPA](http://www.coppa.org/) rules. Until this widget allows easy year selection I'll have to use something else.

Other than the year selection being difficult, I like this widget. It looks nice and it's easy to add to an app. Keep being awesome!

**Comment by chemerisuk** [comment]
Implemented in ecf60ef0f8e7a36111140fcae5ad110077503029
