### ISSUE TITLE
Hide animation is not nice

### ISSUE THREAD

**Issue by rafis** [chemerisuk/better-dateinput-polyfill#82]
Hide animation is:
1. Too fast
2. Not nice, pathetic

Is it possible to replace it with animation from [Air Datepicker](http://t1m0n.name/air-datepicker/docs/index.html)? But this will require also to change show animation as they are always come in pair.

**Comment by chemerisuk** [comment]
You can override default animation in CSS (https://github.com/chemerisuk/better-dom/wiki/Declarative-animations) by customizing `.btr-dateinput-calendar` +  `.btr-dateinput-calendar[aria-hidden=true]`

**Comment by rafis** [comment]
Thank you, I will look into this.

**Comment by rafis** [comment]
As have seen seems your datepicker has ability to be shown from top and be shown from bottom. But seems this option is stored somethere in internal variable and not exposed as class near `.btr-dateinput-calendar`?

**Comment by chemerisuk** [comment]
@rafis correct, I set 'margin-top' depending of viewport in js https://github.com/chemerisuk/better-dateinput-polyfill/blob/master/src/main.js#L281
