### ISSUE TITLE
How to change value programatically?

### ISSUE THREAD

**Issue by rafis** [chemerisuk/better-dateinput-polyfill#83]
I have tried following, but it seems doesn't work. Through according to [documentation](https://github.com/chemerisuk/better-dom/wiki/Getter-and-setter) it should.

    var dateInput = document.querySelectorAll('input[name="date"]')[0];
    dateInput.value = '2016-08-01';

Also I have tried to trigger 'change' event:

    triggerEvent(dateInput, 'change');

    function triggerEvent(element, eventName) {
        var event; // The custom event that will be created

        if (document.createEvent) {
            event = document.createEvent("HTMLEvents");
            event.initEvent(eventName, true, true);
        } else {
            event = document.createEventObject();
            event.eventType = eventName;
        }

        event.eventName = eventName;

        if (document.createEvent) {
            element.dispatchEvent(event);
        } else {
            element.fireEvent("on" + event.eventType, event);
        }
    }

Then I have tried:

    DOM.constructor(dateInput).fire("change");

**Comment by rafis** [comment]
Solved by `dateInput.setAttribute('value', '2016-08-01');`.

**Comment by chemerisuk** [comment]
@rafis please read my comments at https://github.com/chemerisuk/better-dateinput-polyfill/issues/80 - they can be useful
