### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lang' of null

### ISSUE THREAD

**Issue by tim-field** [chemerisuk/better-dateinput-polyfill#85]
Above error is raised in chrome ( latest at least )

From here.
https://github.com/chemerisuk/better-dateinput-polyfill/blob/v2.0.0/dist/better-dateinput-polyfill.js#L19

Reproduce like so in the console 
`window.DOM.get('documentElement');`  -> null

`window.DOM.get('documentElement').lang;` triggers above error.

**Comment by Brookke** [comment]
I am also getting this issue simply doing DOM.get("lang") seems to get the Lang

**Comment by CyrilWork** [comment]
I am not sure if it will work with your case but you can set the lang in the html tag inside your html like this `<html lang="en">`

**Comment by chemerisuk** [comment]
@tim-field it looks like you do not have all dependencies downloaded
