### ISSUE TITLE
'peerinvalid' errors when installing with npm

### ISSUE THREAD

**Issue by davidham** [chemerisuk/better-dateinput-polyfill#88]
I have a project that uses Webpack for JS management. When I try to install better-dateinput-polyfill with `npm install better-dateinput-polyfill --save-dev`, I get the following error:
```
npm ERR! peerinvalid The package better-dom@3.0.0-rc.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer better-dateinput-polyfill@2.0.2 wants better-dom@^3.0.0-rc.1
npm ERR! peerinvalid Peer better-i18n-plugin@2.0.0 wants better-dom@>=2.0.0
npm ERR! peerinvalid Peer better-time-element@1.0.0 wants better-dom@>=2.0.0
```
Looks like the 3.0.0-rc.1  does not satisfy the version requirements for the other three, somehow?

**Comment by chemerisuk** [comment]
Check version 3.0.1
