### ISSUE TITLE
Getting error while running test Task

### ISSUE THREAD

**Issue by parthivshah91** [chemerisuk/better-dateinput-polyfill#94]
Hi 
The plugin is working fine. However, when I cloned repository and executing test task without modification of any code, I am getting below error:

PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  TypeError: undefined is not an object (evaluating 'DOM.get')
  at http://localhost:9877build/better-dateinput-polyfill.js:8

[10:41:29] 'test' errored after 3.85 s
[10:41:29] Error in plugin 'karma'
Message:
    Specs were not passed

**Comment by chemerisuk** [comment]
Hi @parthivshah91. I believe the problem is because of invalid version of better-dom. Fixed in dd47dd1b0d6b2b59ce0fd083582ded7e441f4755

**Comment by parthivshah91** [comment]
I missed bower install ( It would be great if it is mentioned in contrib doc ).
