### ISSUE TITLE
Input doesn't show date (transparent) when controlled by Bootstrap

### ISSUE THREAD

**Issue by sbibauw** [chemerisuk/better-dateinput-polyfill#97]
In my form, when the input `class` is controlled by Boostrap 3.3.7 (e.g. `form-control`, or `col-xs-2`...), the date doesn't appear (it remains transparent, even though it is well recorded when submitting the form). The datepicker works well (appears on front).

    <input type="date" data-format="d MMM yyyy" class="form-control" name="date1">

![screenshot](https://cloud.githubusercontent.com/assets/4708459/24234516/bfff3070-0f66-11e7-86dd-e85efeb555f5.png)
 
If I remove the Bootstrap `class`, the date appears correctly (of course, the CSS is slightly messed up), but now the datepicker appears behind other inputs/selects controlled by Bootstrap:

    <input type="date" data-format="d MMM yyyy" name="date1">

![screenshot](https://cloud.githubusercontent.com/assets/4708459/24234581/26636502-0f67-11e7-9431-6707d3ae86ee.png)

Am I missing something or is it a known bug? (I couldn't find any related issue)

**Edit:** It doesn't seem to appear in all cases, but at least when the `<input>` is inside a `<form class="form-inline">` or a `<div class="input-group">` structure.

**Comment by chemerisuk** [comment]
Should be fixed in version 3
