### ISSUE TITLE
Datepicker drawn under other input fields

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [chemerisuk/better-dateinput-polyfill#98]
I am experiencing an issue when my following inputs have a bootstrap addon.

This does not happen without the addon suffix!

![image](https://cloud.githubusercontent.com/assets/10342708/24838945/f4f0b47c-1d51-11e7-8192-74fda4f60acb.png)

**Comment by alantrick** [comment]
The calendar is created with a z-level of 1, so anything that has a higher z-level will cover it up. I just encountered this with bootstraps "navbar-static-top" class.
